In [28]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import statsmodels.formula.api as smf

In [29]:
dataset = pd.read_csv("/home/agira/Desktop/test1/car performance-dataset.csv")

In [30]:
dataset.head()

mpg  cylinders  displacement  horsepower  weight  acceleration  \
0  18.0          8         307.0         130    3504          12.0   
1  15.0          8         350.0         165    3693          11.5   
2  18.0          8         318.0         150    3436          11.0   
3  16.0          8         304.0         150    3433          12.0   
4  17.0          8         302.0         140    3449          10.5   

   model year  origin                   car name  
0          70       1  chevrolet chevelle malibu  
1          70       1          buick skylark 320  
2          70       1         plymouth satellite  
3          70       1              amc rebel sst  
4          70       1                ford torino

In [31]:
dataset.isnull().any()

mpg             False
cylinders       False
displacement    False
horsepower      False
weight          False
acceleration    False
model year      False
origin          False
car name        False
dtype: bool

In [32]:
dataset.info()#dataset.info() is used to get quick overview of the dataset


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64  
 2   displacement  398 non-null    float64
 3   horsepower    398 non-null    int64  
 4   weight        398 non-null    int64  
 5   acceleration  398 non-null    float64
 6   model year    398 non-null    int64  
 7   origin        398 non-null    int64  
 8   car name      398 non-null    object 
dtypes: float64(3), int64(5), object(1)
memory usage: 28.1+ KB


In [33]:
dataset = dataset.drop('car name',axis=1)

In [34]:
x=dataset[['cylinders','displacement','horsepower','weight','acceleration','model year','origin']].values

In [35]:
print(x)

[[  8.  307.  130.  ...  12.   70.    1. ]
 [  8.  350.  165.  ...  11.5  70.    1. ]
 [  8.  318.  150.  ...  11.   70.    1. ]
 ...
 [  4.  135.   84.  ...  11.6  82.    1. ]
 [  4.  120.   79.  ...  18.6  82.    1. ]
 [  4.  119.   82.  ...  19.4  82.    1. ]]


In [37]:
y=dataset.iloc[:,0:1].values



In [38]:
y

array([[18. ],
       [15. ],
       [18. ],
       [16. ],
       [17. ],
       [15. ],
       [14. ],
       [14. ],
       [14. ],
       [15. ],
       [15. ],
       [14. ],
       [15. ],
       [14. ],
       [24. ],
       [22. ],
       [18. ],
       [21. ],
       [27. ],
       [26. ],
       [25. ],
       [24. ],
       [25. ],
       [26. ],
       [21. ],
       [10. ],
       [10. ],
       [11. ],
       [ 9. ],
       [27. ],
       [28. ],
       [25. ],
       [25. ],
       [19. ],
       [16. ],
       [17. ],
       [19. ],
       [18. ],
       [14. ],
       [14. ],
       [14. ],
       [14. ],
       [12. ],
       [13. ],
       [13. ],
       [18. ],
       [22. ],
       [19. ],
       [18. ],
       [23. ],
       [28. ],
       [30. ],
       [30. ],
       [31. ],
       [35. ],
       [27. ],
       [26. ],
       [24. ],
       [25. ],
       [23. ],
       [20. ],
       [21. ],
       [13. ],
       [14. ],
       [15. ],
       [14. ],
       [17

In [39]:
from sklearn.model_selection import train_test_split

In [59]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=0)

In [60]:
x_train

array([[  6. , 200. ,  85. , ...,  15.8,  78. ,   1. ],
       [  4. ,  78. ,  52. , ...,  19.4,  78. ,   3. ],
       [  4. , 140. ,  88. , ...,  17.3,  79. ,   1. ],
       ...,
       [  4. ,  68. ,  49. , ...,  19.5,  73. ,   2. ],
       [  6. , 250. , 100. , ...,  15. ,  71. ,   1. ],
       [  4. ,  90. ,  71. , ...,  16.5,  75. ,   2. ]])

In [62]:
# from sklearn.preprocessing import StandardScaler
# sd = StandardScaler()
# x__train = sd.fit_transform(x_train)
# x__test = sd.fit_transform(x_test)
# y__train = sd.fit_transform(y_train)
# y__test = sd.fit_transform(y_test)

# x__train

In [63]:
from sklearn.ensemble import RandomForestRegressor

In [64]:
rf= RandomForestRegressor(n_estimators=10,random_state=0)
rf.fit(x_train,y_train.ravel())

RandomForestRegressor(n_estimators=10, random_state=0)

In [65]:
y_pred =rf.predict(x_test)


In [66]:
y_pred

array([13.7 , 24.68, 14.9 , 19.45, 18.5 , 31.6 , 34.17, 20.7 , 14.7 ,
       24.82, 35.92, 35.84, 19.8 , 27.6 , 16.42, 31.16, 27.64, 27.01,
       17.2 , 38.44, 14.95, 23.11, 23.12, 20.01, 31.69, 26.42, 32.28,
       30.51, 31.4 , 16.4 , 19.18, 33.27, 18.22, 33.09, 20.35, 23.96,
       18.43, 16.12, 37.44, 11.7 , 12.9 , 15.2 , 28.03, 32.59, 28.94,
       21.16, 18.33, 14.15, 20.71, 30.  , 33.75, 25.5 , 16.92, 26.  ,
       14.8 , 11.6 , 20.6 , 21.52, 31.33, 15.64, 17.84, 24.45, 19.6 ,
       21.9 , 13.  , 14.4 , 13.1 , 16.9 , 24.16, 12.6 , 36.68, 13.2 ,
       22.  , 18.15, 23.69, 30.03, 28.37, 30.7 , 27.  , 13.9 , 13.8 ,
       28.7 , 31.72, 30.61, 34.53, 37.43, 29.82, 19.75, 29.82, 33.43,
       29.05, 12.9 , 22.8 , 32.82, 31.53, 19.03, 18.33, 25.6 , 20.26,
       13.  ])

In [67]:
from sklearn.metrics import r2_score

In [68]:
accuracy = r2_score(y_test,y_pred)


In [69]:
accuracy

0.8916305495781726

In [70]:
import pickle
pickle.dump(rf,open('regression3.pkl','wb'))